# Generated by Django 4.1.3 on 2022-11-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NRO', models.CharField(max_length=30)),
                ('DUEÑO', models.CharField(max_length=30)),
                ('fono_dueño', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('remitente', models.CharField(max_length=30)),
                ('conserje', models.CharField(max_length=30)),
                ('destinatario', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('numero_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencia')),
            ],
        ),
    ]
